import {readFileSync} from 'node:fs';
import assert from 'node:assert/strict';
import {mountIshihara,renderIshiharaResult} from './ishihara.js';
const sent=[];
const frame={contentWindow:{postMessage:m=>sent.push(m)},style:{}};
let listener,completed=0,calls=0;
globalThis.location={origin:'https://example.test'};
globalThis.document={querySelector:s=>s==='#ishiharaFrame'?frame:{textContent:'',remove(){}}};
globalThis.window={addEventListener:(_,fn)=>{listener=fn;},removeEventListener:(_,fn)=>{if(listener===fn)listener=null;}};
const state={status:'in_progress',revision:0,server_now:new Date().toISOString(),answers:Array(34).fill(null)};
const dispose=await mountIshihara({token:'test',layout:()=>{},onComplete:()=>completed++,rpc:async(name,p)=>{
  if(name==='ishihara_session')return state;
  calls++;assert.equal(p.p_revision,0);
  return {...state,revision:1,status:p.p_finish?'completed':'in_progress'};
}});
const event=data=>({origin:location.origin,source:frame.contentWindow,data});
await listener({origin:'https://other.test',source:frame.contentWindow,data:{type:'ishihara-save'}});
assert.equal(calls,0);
await listener(event({type:'ishihara-ready'}));
assert.equal(sent.at(-1).answers.length,34);
await listener(event({type:'ishihara-save',id:1,answers:state.answers,finish:true}));
assert.equal(sent.at(-1).type,'ishihara-ack');
await listener(event({type:'ishihara-complete'}));
await listener(event({type:'ishihara-complete'}));
assert.equal(completed,1);
dispose();assert.equal(listener,null);
const html=renderIshiharaResult({status:'completed'},[{question_number:1,answer:{choice:'<script>'}}]);
assert(!html.includes('<script>'));assert(html.includes('&lt;script&gt;'));assert(html.includes('0/22'));
console.log('PASS: trusted frame messages, revision, finish-once, cleanup, escaped report');

const headers=readFileSync(new URL('./_headers',import.meta.url),'utf8');
assert(headers.includes('X-Frame-Options: SAMEORIGIN'));
assert(headers.includes("frame-src 'self'; frame-ancestors 'self'"));
assert(!headers.includes("'unsafe-inline' https://cdn.jsdelivr.net"));
const frameHtml=readFileSync(new URL('./ishihara-frame.html',import.meta.url),'utf8');
assert(!/<script\s*>/.test(frameHtml));
assert(frameHtml.includes('src="ishihara-frame.js?v=20261009-direct"'));
assert(readFileSync(new URL('./ishihara-frame.js',import.meta.url),'utf8').includes("type:'ishihara-ready'"));
assert.equal(frame.src,'ishihara-frame.html?v=20261009-direct');
console.log('PASS: same-origin framing, external script, versioned frame navigation');
