import assert from 'node:assert/strict';
import {mapPersonality} from './scoring.js';
import {renderResult} from './results.js';
const reference={test1:[{number:1,options:['Saya seorang pekerja keras','Saya bukan seorang pemurung']}],test2:[{number:1,options:['Aktif merubah sesuatu hal','Bekerja dengan cepat, tekup','Berpikir logis, Sistimatis','Ramah']} ]};
const config={reference};
const papi={question_snapshot:[{number:9,options:['Saya <em>bukan</em> seorang pemurung','Saya seorang <strong>pekerja keras</strong>']}]};
assert.deepEqual(mapPersonality('test1',papi,[{question_number:9,answer:{choice:0}}],config),{values:[2],issues:[]});
const disc={question_snapshot:[{number:8,options:['Ramah','Berpikir logis, sistematis','Bekerja dengan cepat, tekun','Aktif merubah sesuatu hal-hal']}]};
assert.deepEqual(mapPersonality('test2',disc,[{question_number:8,answer:{most:3,least:2}}],config),{values:[{most:0,least:1}],issues:[]});
const changed={question_snapshot:[{number:9,options:['Makna baru','Saya seorang pekerja keras']}]};
assert.deepEqual(mapPersonality('test1',changed,[{question_number:9,answer:{choice:0}}],config).issues,[9]);
assert.deepEqual(mapPersonality('test1',papi,[{question_number:9,answer:{choice:99}}],config).issues,[9]);
const rules=Object.fromEntries([...'NGALPITVSBOXCDRZEKFW'].map(k=>[k,[[1,1]]]));
config.papi={rules,reversedChart:['K','Z'],descriptions:Object.fromEntries(Object.keys(rules).map(k=>[k,[[''],['Uraian']]]))};
const html=renderResult('test1',{...papi,status:'completed'},[{question_number:9,answer:{choice:1}}],config);
assert(html.includes('class="papi-chart"'));assert(!html.includes('Grafik belum dihitung'));
assert(renderResult('test1',{...papi,status:'completed'},[{question_number:9,answer:{choice:1}}],{}).includes('Hasil sesi lain tetap tersedia'));
assert(renderResult('test1',{...papi,status:'completed'},[{question_number:9,answer:{choice:1}}],config).includes('class="papi-chart"'));
console.log('PASS: emphasis, reviewed DISC aliases, reordered options, unknown changes blocked, PAPI render');
