-- Gamatex MBTI: 70 soal berdasarkan MBTI V2,1 Open.xlsx
-- Jalankan setelah migrasi question_bank/test_settings tersedia.

begin;

delete from public.question_bank where test_code = 'mbti';

insert into public.question_bank (test_code, question_number, question_type, prompt, options, duration_seconds, active, image_url) values ('mbti', 1, 'paired_choice', 'Saat berada di sebuah pesta, Anda:', '["Berinteraksi dengan banyak orang, termasuk yang belum dikenal.", "Berinteraksi hanya dengan beberapa orang yang sudah dikenal"]'::jsonb, 20, true, null);
insert into public.question_bank (test_code, question_number, question_type, prompt, options, duration_seconds, active, image_url) values ('mbti', 2, 'paired_choice', 'Apakah Anda termasuk orang yang:', '["Cenderung realistis", "Cenderung spekulatif"]'::jsonb, 20, true, null);
insert into public.question_bank (test_code, question_number, question_type, prompt, options, duration_seconds, active, image_url) values ('mbti', 3, 'paired_choice', 'Keadaan mana yang lebih buruk :', '["penuh dengan angan-angan", "terbatasi oleh  fakta-fakta"]'::jsonb, 20, true, null);
insert into public.question_bank (test_code, question_number, question_type, prompt, options, duration_seconds, active, image_url) values ('mbti', 4, 'paired_choice', 'Apakah Anda lebih terkesan oleh :', '["Teori-teori", "Emosi dan perasaan"]'::jsonb, 20, true, null);
insert into public.question_bank (test_code, question_number, question_type, prompt, options, duration_seconds, active, image_url) values ('mbti', 5, 'paired_choice', 'Apakah Anda lebih tertarik pada orang yang:', '["Meyakinkan Anda", "Menyentuh perasaan Anda"]'::jsonb, 20, true, null);
insert into public.question_bank (test_code, question_number, question_type, prompt, options, duration_seconds, active, image_url) values ('mbti', 6, 'paired_choice', 'Apakah Anda lebih menyukai bekerja', '["dengan tenggat waktu (deadline)", "kapan saja Anda mau"]'::jsonb, 20, true, null);
insert into public.question_bank (test_code, question_number, question_type, prompt, options, duration_seconds, active, image_url) values ('mbti', 7, 'paired_choice', 'Apakah Anda cenderung memilih sesuatu', '["dengan penuh perhitungan", "secara impulsif"]'::jsonb, 20, true, null);
insert into public.question_bank (test_code, question_number, question_type, prompt, options, duration_seconds, active, image_url) values ('mbti', 8, 'paired_choice', 'Di dalam pesta, apakah Anda:', '["hadir sampai larut, dengan lebih bersemangat", "pulang lebih awal, dengan kehabisan energi"]'::jsonb, 20, true, null);
insert into public.question_bank (test_code, question_number, question_type, prompt, options, duration_seconds, active, image_url) values ('mbti', 9, 'paired_choice', 'Apakah Anda lebih tertarik pada', '["orang yang konkrit, atau", "orang yang memiliki imajinasi"]'::jsonb, 20, true, null);
insert into public.question_bank (test_code, question_number, question_type, prompt, options, duration_seconds, active, image_url) values ('mbti', 10, 'paired_choice', 'Anda lebih tertarik pada:', '["hal-hal yang aktual", "hal-hal yang mungkin terjadi"]'::jsonb, 20, true, null);
insert into public.question_bank (test_code, question_number, question_type, prompt, options, duration_seconds, active, image_url) values ('mbti', 11, 'paired_choice', 'Dalam menilai orang, apakah Anda lebih dipengaruhi oleh:', '["hukum-hukum atau peraturan", "kemungkinan-kemungkinan"]'::jsonb, 20, true, null);
insert into public.question_bank (test_code, question_number, question_type, prompt, options, duration_seconds, active, image_url) values ('mbti', 12, 'paired_choice', 'Dalam mendekati orang lain, apakah Anda cenderung bersikap', '["formal, obyektif", "personal/pribadi"]'::jsonb, 20, true, null);
insert into public.question_bank (test_code, question_number, question_type, prompt, options, duration_seconds, active, image_url) values ('mbti', 13, 'paired_choice', 'Dalam melakukan sesuatu, apakah anda cenderung', '["Terikat pada waktu", "Santai"]'::jsonb, 20, true, null);
insert into public.question_bank (test_code, question_number, question_type, prompt, options, duration_seconds, active, image_url) values ('mbti', 14, 'paired_choice', 'Mana yang lebih mengganggu Anda; hal-hal yang', '["belum terselesaikan", "sudah terselesaikan"]'::jsonb, 20, true, null);
insert into public.question_bank (test_code, question_number, question_type, prompt, options, duration_seconds, active, image_url) values ('mbti', 15, 'paired_choice', 'Dalam kelompok sosial Anda, apakah Anda', '["selalu mengetahui perkembangan kondisi  teman-teman Anda", "tidak mengikuti informasi keadaan teman-teman Anda"]'::jsonb, 20, true, null);
insert into public.question_bank (test_code, question_number, question_type, prompt, options, duration_seconds, active, image_url) values ('mbti', 16, 'paired_choice', 'Dalam melakukan hal-hal sehari-hari, apakah Anda cenderung', '["melakukannya seperti kebanyakan orang", "melakukannya dengan cara Anda sendiri"]'::jsonb, 20, true, null);
insert into public.question_bank (test_code, question_number, question_type, prompt, options, duration_seconds, active, image_url) values ('mbti', 17, 'paired_choice', 'Menurut Anda, penulis sebaiknya', '["menulis seperti apa yang mereka maksudkan", "menulis dengan menggunakan analogi atau lambang-lambang"]'::jsonb, 20, true, null);
insert into public.question_bank (test_code, question_number, question_type, prompt, options, duration_seconds, active, image_url) values ('mbti', 18, 'paired_choice', 'Mana yang lebih menarik bagi Anda', '["konsistensi pemikiran", "hubungan antar manusia yang harmonis"]'::jsonb, 20, true, null);
insert into public.question_bank (test_code, question_number, question_type, prompt, options, duration_seconds, active, image_url) values ('mbti', 19, 'paired_choice', 'Apakah Anda lebih suka membuat', '["penilaian berdasarkan pemikiran yang logis", "penilaian berdasarkan norma-norma yang berlaku di masyarakat"]'::jsonb, 20, true, null);
insert into public.question_bank (test_code, question_number, question_type, prompt, options, duration_seconds, active, image_url) values ('mbti', 20, 'paired_choice', 'Apakah Anda lebih menyukai hal-hal di  sekitar Anda', '["tersusun dan terjadwal", "tidak tersusun dan tidak terjadwal"]'::jsonb, 20, true, null);
insert into public.question_bank (test_code, question_number, question_type, prompt, options, duration_seconds, active, image_url) values ('mbti', 21, 'paired_choice', 'Apakah Anda cenderung termasuk orang yang', '["Serius dan berkemauan keras", "Santai (easy going)"]'::jsonb, 20, true, null);
insert into public.question_bank (test_code, question_number, question_type, prompt, options, duration_seconds, active, image_url) values ('mbti', 22, 'paired_choice', 'Saat menelepon seseorang, apakah Anda', '["tidak merencanakan apa yang akan dibicarakan", "melatih/mengulang hal-hal yang akan dibicarakan"]'::jsonb, 20, true, null);
insert into public.question_bank (test_code, question_number, question_type, prompt, options, duration_seconds, active, image_url) values ('mbti', 23, 'paired_choice', 'Fakta, menurut Anda', '["menyatakan hal yang terjadi", "mengggambarkan prinsip-prinsip"]'::jsonb, 20, true, null);
insert into public.question_bank (test_code, question_number, question_type, prompt, options, duration_seconds, active, image_url) values ('mbti', 24, 'paired_choice', 'Menurut Anda,seorang visioner', '["mengganggu", "mengagumkan"]'::jsonb, 20, true, null);
insert into public.question_bank (test_code, question_number, question_type, prompt, options, duration_seconds, active, image_url) values ('mbti', 25, 'paired_choice', 'Apakah Anda cenderung', '["berkepala dingin, atau", "ramah dan  hangat"]'::jsonb, 20, true, null);
insert into public.question_bank (test_code, question_number, question_type, prompt, options, duration_seconds, active, image_url) values ('mbti', 26, 'paired_choice', 'Mana yang lebih buruk:', '["ketidak adilan", "tanpa belas kasih"]'::jsonb, 20, true, null);
insert into public.question_bank (test_code, question_number, question_type, prompt, options, duration_seconds, active, image_url) values ('mbti', 27, 'paired_choice', 'Apakah seseorang sebaiknya menjalani kejadian dalam hidupnya sebagai:', '["suatu akibat dari kegiatan dan/atau pilihan yang dibuat sebelumnya", "sesuatu yang terjadi secara kebetulan"]'::jsonb, 20, true, null);
insert into public.question_bank (test_code, question_number, question_type, prompt, options, duration_seconds, active, image_url) values ('mbti', 28, 'paired_choice', 'Apakah Anda merasa lebih suka', '["dibelikan sesuatu barang", "memiliki pilihan untuk membeli"]'::jsonb, 20, true, null);
insert into public.question_bank (test_code, question_number, question_type, prompt, options, duration_seconds, active, image_url) values ('mbti', 29, 'paired_choice', 'Saat bersama orang lain, Anda lebih suka:', '["memulai pembicaraan", "menunggu orang lain berbicara pada Anda"]'::jsonb, 20, true, null);
insert into public.question_bank (test_code, question_number, question_type, prompt, options, duration_seconds, active, image_url) values ('mbti', 30, 'paired_choice', 'Nalar, menurut Anda', '["tak perlu dipertanyakan", "patut  dipertanyakan"]'::jsonb, 20, true, null);
insert into public.question_bank (test_code, question_number, question_type, prompt, options, duration_seconds, active, image_url) values ('mbti', 31, 'paired_choice', 'Anak-anak seringkali :', '["kurang membuat diri mereka berguna bagi orang lain", "tidak cukup melatih/mengembang-kan fantasi mereka"]'::jsonb, 20, true, null);
insert into public.question_bank (test_code, question_number, question_type, prompt, options, duration_seconds, active, image_url) values ('mbti', 32, 'paired_choice', 'Dalam membuat keputusan, apakah Anda lebih suka menggunakan', '["standar/peraturan", "perasaan"]'::jsonb, 20, true, null);
insert into public.question_bank (test_code, question_number, question_type, prompt, options, duration_seconds, active, image_url) values ('mbti', 33, 'paired_choice', 'Apakah Anda cenderung orang yang', '["tegas, atau", "lemah lembut"]'::jsonb, 20, true, null);
insert into public.question_bank (test_code, question_number, question_type, prompt, options, duration_seconds, active, image_url) values ('mbti', 34, 'paired_choice', 'Mana yang lebih patut dihormati:', '["kemampuan untuk mengorganisasi dan mengatur", "kemampuan untuk beradaptasi"]'::jsonb, 20, true, null);
insert into public.question_bank (test_code, question_number, question_type, prompt, options, duration_seconds, active, image_url) values ('mbti', 35, 'paired_choice', 'Apakah Anda lebih menekankan pentingnya:', '["kepastian", "kemungkinan"]'::jsonb, 20, true, null);
insert into public.question_bank (test_code, question_number, question_type, prompt, options, duration_seconds, active, image_url) values ('mbti', 36, 'paired_choice', 'Interaksi yang baru dengan orang lain yang belum dikenal  membuat Anda:', '["bersemangat dan bergairah", "merasa lelah dan kehabisan energi"]'::jsonb, 20, true, null);
insert into public.question_bank (test_code, question_number, question_type, prompt, options, duration_seconds, active, image_url) values ('mbti', 37, 'paired_choice', 'Apakah Anda lebih cenderung orang yang', '["praktis", "penuh angan-angan"]'::jsonb, 20, true, null);
insert into public.question_bank (test_code, question_number, question_type, prompt, options, duration_seconds, active, image_url) values ('mbti', 38, 'paired_choice', 'Apakah Anda lebih sering', '["memperhatikan apa yang bisa dilakukan orang lain", "memperhatikan apa yang menjadi pusat perhatian orang lain"]'::jsonb, 20, true, null);
insert into public.question_bank (test_code, question_number, question_type, prompt, options, duration_seconds, active, image_url) values ('mbti', 39, 'paired_choice', 'Mana yang lebih memuaskan Anda:', '["mendiskusikan suatu topik secara mendalam", "mencapai sebuah persetujuan atas suatu topik/masalah"]'::jsonb, 20, true, null);
insert into public.question_bank (test_code, question_number, question_type, prompt, options, duration_seconds, active, image_url) values ('mbti', 40, 'paired_choice', 'Mana yang lebih berperan dalam diri Anda:', '["kepala/pikiran Anda", "hati Anda"]'::jsonb, 20, true, null);
insert into public.question_bank (test_code, question_number, question_type, prompt, options, duration_seconds, active, image_url) values ('mbti', 41, 'paired_choice', 'Apakah Anda lebih menyukai pekerjaan yang berbasis:', '["kontrak", "permanen"]'::jsonb, 20, true, null);
insert into public.question_bank (test_code, question_number, question_type, prompt, options, duration_seconds, active, image_url) values ('mbti', 42, 'paired_choice', 'Anda cenderung lebih suka mengerjakan:', '["hal yang sudah tersusun/terjadwal", "hal apa pun yang muncul di hadapan Anda"]'::jsonb, 20, true, null);
insert into public.question_bank (test_code, question_number, question_type, prompt, options, duration_seconds, active, image_url) values ('mbti', 43, 'paired_choice', 'Mana yang lebih Anda sukai:', '["memiliki banyak teman dengan sesekali kontak", "memiliki sedikit teman dengan intensitas kontak yang mendalam"]'::jsonb, 20, true, null);
insert into public.question_bank (test_code, question_number, question_type, prompt, options, duration_seconds, active, image_url) values ('mbti', 44, 'paired_choice', 'Apakah Anda lebih dipengaruhi oleh', '["Fakta, atau", "Teori-teori/ prinsip"]'::jsonb, 20, true, null);
insert into public.question_bank (test_code, question_number, question_type, prompt, options, duration_seconds, active, image_url) values ('mbti', 45, 'paired_choice', 'Anda lebih tertarik pada sifat pekerjaan:', '["produksi dan distribusi", "desain dan penelitian"]'::jsonb, 20, true, null);
insert into public.question_bank (test_code, question_number, question_type, prompt, options, duration_seconds, active, image_url) values ('mbti', 46, 'paired_choice', 'Mana yang lebih merupakan suatu pujian bagi Anda:', '["“Anda orang yang sangat logis”", "“Anda orang yang sangat berperasaan”"]'::jsonb, 20, true, null);
insert into public.question_bank (test_code, question_number, question_type, prompt, options, duration_seconds, active, image_url) values ('mbti', 47, 'paired_choice', 'Hal yang Anda hargai dari diri Anda adalah bahwa Anda termasuk orang yang:', '["pasti, dapat diprediksi", "loyal, rajin"]'::jsonb, 20, true, null);
insert into public.question_bank (test_code, question_number, question_type, prompt, options, duration_seconds, active, image_url) values ('mbti', 48, 'paired_choice', 'Apakah Anda lebih menyukai', '["hal-hal yang sudah terselesaikan dan tidak dapat diubah kembal", "hal-hal yang belum terselesaikan dan bersifat sementara"]'::jsonb, 20, true, null);
insert into public.question_bank (test_code, question_number, question_type, prompt, options, duration_seconds, active, image_url) values ('mbti', 49, 'paired_choice', 'Apakah Anda lebih merasa nyaman', '["sebelum suatu keputusan diambil", "setelah suatu keputusan diambil"]'::jsonb, 20, true, null);
insert into public.question_bank (test_code, question_number, question_type, prompt, options, duration_seconds, active, image_url) values ('mbti', 50, 'paired_choice', 'Apakah Anda', '["mudah membangun pembicaraan yang mendalam dengan orang yang belum dikenal", "kurang merasa nyaman berbicara dengan orang yang belum dikenal"]'::jsonb, 20, true, null);
insert into public.question_bank (test_code, question_number, question_type, prompt, options, duration_seconds, active, image_url) values ('mbti', 51, 'paired_choice', 'Apakah Anda lebih mempercayai', '["pengalaman Anda", "prediksi/perkiraan Anda"]'::jsonb, 20, true, null);
insert into public.question_bank (test_code, question_number, question_type, prompt, options, duration_seconds, active, image_url) values ('mbti', 52, 'paired_choice', 'Apakah Anda merasa bahwa Anda', '["cenderung praktis", "cenderung cerdik"]'::jsonb, 20, true, null);
insert into public.question_bank (test_code, question_number, question_type, prompt, options, duration_seconds, active, image_url) values ('mbti', 53, 'paired_choice', 'Orang seperti apa yang menurut Anda lebih patut dihargai, apakah mereka yang:', '["memiliki alasan yang jelas, atau", "memiliki perasaan yang kuat"]'::jsonb, 20, true, null);
insert into public.question_bank (test_code, question_number, question_type, prompt, options, duration_seconds, active, image_url) values ('mbti', 54, 'paired_choice', 'Apakah Anda cenderung', '["berpikir adil", "bersimpati pada orang lain"]'::jsonb, 20, true, null);
insert into public.question_bank (test_code, question_number, question_type, prompt, options, duration_seconds, active, image_url) values ('mbti', 55, 'paired_choice', 'Akan lebih baik jika manusia', '["mengatur agar hal dan peristiwa  terjadi seperti yang diinginkan", "membiarkan peristiwa terjadi apa adanya"]'::jsonb, 20, true, null);
insert into public.question_bank (test_code, question_number, question_type, prompt, options, duration_seconds, active, image_url) values ('mbti', 56, 'paired_choice', 'Dalam hubungan antar manusia, suatu kejadian sebaiknya', '["dapat diatur kemunculannya", "terjadi secara kebetulan dan tak terduga"]'::jsonb, 20, true, null);
insert into public.question_bank (test_code, question_number, question_type, prompt, options, duration_seconds, active, image_url) values ('mbti', 57, 'paired_choice', 'Saat telepon berbunyi, Anda', '["bergegas mengangkatnya", "berharap orang lain akan mengangkatnya"]'::jsonb, 20, true, null);
insert into public.question_bank (test_code, question_number, question_type, prompt, options, duration_seconds, active, image_url) values ('mbti', 58, 'paired_choice', 'Mana yang lebih Anda hargai dari diri Anda:', '["kemampuan untuk berpikir realistis", "imajinasi yang kuat"]'::jsonb, 20, true, null);
insert into public.question_bank (test_code, question_number, question_type, prompt, options, duration_seconds, active, image_url) values ('mbti', 59, 'paired_choice', 'Apakah Anda lebih tertarik pada:', '["hal-hal yang mendasar", "makna atau nuansa yang dikandung oleh sesuatu"]'::jsonb, 20, true, null);
insert into public.question_bank (test_code, question_number, question_type, prompt, options, duration_seconds, active, image_url) values ('mbti', 60, 'paired_choice', 'Kesalahan mana yang lebih berat:', '["terlalu berperasaan", "terlalu obyektif"]'::jsonb, 20, true, null);
insert into public.question_bank (test_code, question_number, question_type, prompt, options, duration_seconds, active, image_url) values ('mbti', 61, 'paired_choice', 'Apakah Anda melihat diri Anda sebagai orang yang', '["keras kepala", "berhati lembut"]'::jsonb, 20, true, null);
insert into public.question_bank (test_code, question_number, question_type, prompt, options, duration_seconds, active, image_url) values ('mbti', 62, 'paired_choice', 'Situasi mana yang lebih menarik bagi Anda:', '["terstruktur dan terjadwal", "tidak terstruktur dan tidak terjadwal"]'::jsonb, 20, true, null);
insert into public.question_bank (test_code, question_number, question_type, prompt, options, duration_seconds, active, image_url) values ('mbti', 63, 'paired_choice', 'Apakah Anda termasuk orang yang cenderung', '["rutin dan teratur, atau", "mudah berubah, tidak terduga"]'::jsonb, 20, true, null);
insert into public.question_bank (test_code, question_number, question_type, prompt, options, duration_seconds, active, image_url) values ('mbti', 64, 'paired_choice', 'Apakah Anda cenderung', '["mudah didekati orang lain", "penyendiri, pendiam"]'::jsonb, 20, true, null);
insert into public.question_bank (test_code, question_number, question_type, prompt, options, duration_seconds, active, image_url) values ('mbti', 65, 'paired_choice', 'Dalam menulis, apakah Anda lebih menyukai tulisan yang bersifat:', '["literal, mengungkapkan fakta", "figuratif, mengandung banyak makna"]'::jsonb, 20, true, null);
insert into public.question_bank (test_code, question_number, question_type, prompt, options, duration_seconds, active, image_url) values ('mbti', 66, 'paired_choice', 'Mana yang lebih sulit bagi Anda', '["mendekatkan diri dengan orang lain", "mendaya gunakan orang lain"]'::jsonb, 20, true, null);
insert into public.question_bank (test_code, question_number, question_type, prompt, options, duration_seconds, active, image_url) values ('mbti', 67, 'paired_choice', 'Anda berharap Anda lebih memiliki:', '["kemampuan untuk berpikir logis", "perasaan  yang lebih halus dan peka"]'::jsonb, 20, true, null);
insert into public.question_bank (test_code, question_number, question_type, prompt, options, duration_seconds, active, image_url) values ('mbti', 68, 'paired_choice', 'Kesalahan mana yang lebih besar:', '["bersikap tidak membedakan orang lain", "bersikap kritis"]'::jsonb, 20, true, null);
insert into public.question_bank (test_code, question_number, question_type, prompt, options, duration_seconds, active, image_url) values ('mbti', 69, 'paired_choice', 'Apakah Anda lebih menyukai', '["peristiwa yang sudah direncanakan", "peristiwa yang tidak direncanakan"]'::jsonb, 20, true, null);
insert into public.question_bank (test_code, question_number, question_type, prompt, options, duration_seconds, active, image_url) values ('mbti', 70, 'paired_choice', 'Apakah Anda cenderung lebih:', '["terencana, atau", "spontan"]'::jsonb, 20, true, null);

insert into public.test_settings (test_code, display_name, active, sort_order, session_duration_seconds, updated_at)
select 'mbti', 'MBTI', true, coalesce(max(sort_order),0)+1, null, now() from public.test_settings
on conflict (test_code) do update set display_name=excluded.display_name, updated_at=now();

commit;
